#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'jobtracker_types'

      module Hadoop
        module API
          module Jobtracker
    end
  end
end
